shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
scrolling:
  history: 10000
  multiplier: 3
  auto_scroll: true

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrains Mono Nerd Font
    style: Bold

  italic:
    family: JetBrains Mono Nerd Font
    style: Italic

  bold_italic:
    family: Jetbrains Mono Nerd Font
    style: Bold Italic

  size: 11
